Ques 1) Basic NumPy Array
A) Reverse the NumPy array: arr = arr = np.array([1,2,3,6,4,5])

In [1]:
import numpy as np
arr = np.array([1,2,3,6,4,5])
arr = arr[::-1]
arr

array([5, 4, 6, 3, 2, 1])

B) Flatten the NumPy arr: array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) using any two NumPy in-built methods



In [2]:
array = np.array([[1,2,3],[2,4,5],[1,2,3]])
flat_arr = array.flatten(order = 'C')
flat_array = array.ravel(order = 'F')
print(flat_arr)
print(flat_array)

[1 2 3 2 4 5 1 2 3]
[1 2 1 2 4 2 3 5 3]


C) Compare the following numpy arrays: np.array([1, 2, 3, 6, 4, 5]) np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])



In [3]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
print(arr1 == arr2)

[[ True  True]
 [ True  True]]


D) Find the most frequent value and their indice(s) in the following arrays: x = np.array([1,2,3,4,5,1,2,1,1,1]) y = np.array([1,1,1,2,3,4,2,4,3,3])

In [6]:
x = np.array([1,2,3,4,5,1,2,1,1,1])
values_x,counts_x = np.unique(x,return_counts=True)
most_freq_x = values_x[np.argmax(counts_x)]
indices = np.where(x == most_freq_x)[0]
print(indices)
print(most_freq_x)
print()

y = np.array([1,1,1,2,3,4,2,4,3,3,])
values_y,counts_y = np.unique(y,return_counts=True)
most_freq_y = values_y[np.argmax(counts_y)]
indices = np.where(y == most_freq_y)[0]
print(indices)
print(most_freq_y)
print()

[0 5 7 8 9]
1

[0 1 2]
1



E) For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]') i. Sum of all elements ii. Sum of all elements row-wise iii. Sum of all elements column-wise

In [7]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')

# Total Sum
print(gfg.sum())
print()

# Row Wise Sum
print(gfg.sum(axis=1))
print()

# Col Wise Sum
print(gfg.sum(axis=0))
print()

45

[[14]
 [16]
 [15]]

[[20  9 16]]



F) For the matrix: n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]]), find i. Sum of diagonal elements ii. Eigen values of matrix iii. Eigen vectors of matrix iv. Inverse of matrix v. Determinant of matrix

In [8]:
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])

# Sum of diagonals
sumDiag = np.trace(n_array)
print(sumDiag)
print()

# Eigen Values
eigenValues = np.linalg.eigvals(n_array)
print(eigenValues)
print()

# Eigen Vectors
eigenVectors = np.linalg.eig(n_array)
print(eigenVectors)
print()

#Inverse of Matrix
invMat = np.linalg.inv(n_array)
print(invMat)
print()

#Determinant of Matrix
det = np.linalg.det(n_array)
print(det)

176

[98.16835147 28.097044   49.73460452]

EigResult(eigenvalues=array([98.16835147, 28.097044  , 49.73460452]), eigenvectors=array([[ 0.4574917 ,  0.34637121, -0.15017693],
       [ 0.28447814, -0.72784061, -0.4852124 ],
       [ 0.84248058,  0.59184038,  0.8614034 ]]))

[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]

137180.0000000001


G) Multiply the following matrices and also find covariance between matrices using NumPy: i. p = [[1, 2], [2, 3]] q = [[4, 5], [6, 7]] ii. p = [[1, 2], [2, 3], [4, 5]] q = [[4, 5, 1], [6, 7, 2]]

In [5]:
p = np.array([[1, 2], [2, 3]])
q = np.array([[4, 5], [6, 7]])

# Multiplication of Matrix
result = p @ q
print(result)
print()

# Co-Variance
coVar = np.cov(p.flatten(), q.flatten())
print(coVar)
print()

print()
print()

p = np.array([[1, 2], [2, 3], [4, 5]])
q = np.array([[4, 5, 1], [6, 7, 2]])

# Multiplication of Matrix
result = p @ q
print(result)
print()

# Co-Variance
coVar = np.cov(p.flatten(), q.flatten())
print(coVar)
print()

[[16 19]
 [26 31]]

[[0.66666667 1.        ]
 [1.         1.66666667]]



[[16 19  5]
 [26 31  8]
 [46 55 14]]

[[2.16666667 0.23333333]
 [0.23333333 5.36666667]]



H) For the matrices: x = np.array([[2, 3, 4], [3, 2, 9]]); y = np.array([[1, 5, 0], [5, 10, 3]]), find inner, outer and cartesian product

In [4]:
x = np.array([[2, 3, 4],
              [3, 2, 9]])
y = np.array([[1, 5, 0],
              [5, 10, 3]])

# Inner Cartesian
inner = np.inner(x, y)
print(inner)
print()

# Outer Cartesian
outer = np.outer(x, y)
print(outer)
print()

# Cartesian
from itertools import product
cartesian = np.array([np.concatenate((a, b)) for a, b in product(x,y)])
print(cartesian)
print()

[[17 52]
 [13 62]]

[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]

[[ 2  3  4  1  5  0]
 [ 2  3  4  5 10  3]
 [ 3  2  9  1  5  0]
 [ 3  2  9  5 10  3]]



Ques 2) Based on NumPy Mathematics and Statistics
(a) For the array: array = np.array([[1, -2, 3],[-4, 5, -6]]) i. Find element-wise absolute value ii. Find the 25th, 50th, and 75th percentile of flattened array, for each column, for each row. iii. Mean, Median and Standard Deviation of flattened array, of each column, and each row

In [9]:
array = np.array([[1, -2, 3],
                  [-4, 5, -6]])

# Element wise absolute value --- (i)
abs_array = np.abs(array)
print(abs_array)
print()

[[1 2 3]
 [4 5 6]]



In [10]:
# For Flattened Array,for each column,for each row --- (ii)
flat = array.flatten()

# flat array
p25_flat = np.percentile(flat,25)
p50_flat = np.percentile(flat,50)
p75_flat = np.percentile(flat,75)

print(p25_flat)
print(p50_flat)
print(p75_flat)
print()

# Column Wise
p25_col = np.percentile(array,25,axis=0)
p50_col = np.percentile(array,50,axis=0)
p75_col = np.percentile(array,75,axis=0)

print(p25_col)
print(p50_col)
print(p75_col)
print()

# Row Wise
p25_row = np.percentile(array,25,axis=1)
p50_row = np.percentile(array,50,axis=1)
p75_row = np.percentile(array,75,axis=1)

print(p25_row)
print(p50_row)
print(p75_row)
print()

-3.5
-0.5
2.5

[-2.75 -0.25 -3.75]
[-1.5  1.5 -1.5]
[-0.25  3.25  0.75]

[-0.5 -5. ]
[ 1. -4.]
[2.  0.5]



In [11]:
# Mean, Median and Standard Deviation of flattened array, of each column, and each row --- (iii)
# flat array
mean_flat = np.mean(array)
median_flat = np.median(array)
std_flat = np.std(array)

print(mean_flat)
print(median_flat)
print(std_flat)
print()

# Column Wise
mean_col = np.mean(array, axis=0)
median_col = np.median(array, axis=0)
std_col = np.std(array, axis=0)

print(mean_col)
print(median_col)
print(std_col)
print()

# Row Wise
mean_row = np.mean(array, axis=1)
median_row = np.median(array, axis=1)
std_row = np.std(array, axis=1)

print(mean_row)
print(median_row)
print(std_row)
print()

-0.5
-0.5
3.8622100754188224

[-1.5  1.5 -1.5]
[-1.5  1.5 -1.5]
[2.5 3.5 4.5]

[ 0.66666667 -1.66666667]
[ 1. -4.]
[2.05480467 4.78423336]



(b) For the array: a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0]). Find floor, ceiling and truncated value, rounded values

In [12]:
a = np.array([-1.8,-1.6,-0.5,0.5,1.6,1.8,3.0])

A_floor = np.floor(a)
A_ceiling = np.ceil(a)
A_truncated = np.trunc(a)
A_rounded = np.round(a)

print(A_floor)
print(A_ceiling)
print(A_truncated)
print(A_rounded)

[-2. -2. -1.  0.  1.  1.  3.]
[-1. -1. -0.  1.  2.  2.  3.]
[-1. -1. -0.  0.  1.  1.  3.]
[-2. -2. -0.  0.  2.  2.  3.]


Ques 3) Based on Searching and Sorting
(a) For the array: array = np.array([10, 52, 62, 16, 16, 54, 453]),find i. Sorted array ii. Indices of sorted array iii. 4 smallest elements iv. 5 largest elements

In [13]:
Arr = np.array([10,52,62,16,16,54,453])
#(i)
sorted_Arr = np.sort(Arr)
print(sorted_Arr)

#(ii)
sorted_indices = np.argsort(Arr)
print(sorted_indices)

#(iii)
smallest_4 = np.sort(Arr)[:4]
print(smallest_4)

#(iv)
largest_5 = np.sort(Arr)[-5:]
print(largest_5)

[ 10  16  16  52  54  62 453]
[0 3 4 1 5 2 6]
[10 16 16 52]
[ 16  52  54  62 453]


(b) For the array: array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0]), find i. Integer elements only ii. Float elements only

In [14]:
Array = np.array([1.0,1.2,2.2,2.0,3.0,2.0])
#(i)
integer_only = Array[Array == Array.astype(int)]
print(integer_only)

#(ii)
float_only = Array[Array != Array.astype(int)]
print(float_only)

[1. 2. 3. 2.]
[1.2 2.2]


Ques 4) Based on Function to save Image
Write a function named img_to_array(path) that reads an image from a specified path and save it as text file on local machine? (Note: use separate cases for RGB and Grey Scale images)

In [15]:
import cv2
import os

def img_to_array(path):
    img = cv2.imread(path, cv2.IMREAD_UNCHANGED)
    if img is None:
        print("Error: Image not found or unable to read.")
        return

    if len(img.shape) == 2:
        print("Image is grayscale.")

        txt_filename = os.path.splitext(path)[0] + "_grayscale.txt"
        np.savetxt(txt_filename,img,fmt='%d')
        print(f"Grayscale image saved as text file: {txt_filename}")

    elif len(img.shape) == 3 and img.shape[2] == 3:
        print("Image is color (BGR).")

        img_rgb = cv2.cvtColor(img,cv2.COLOR_BGR2RGB)

        txt_filename = os.path.splitext(path)[0] + "_rgb.txt"

        reshaped = img_rgb.reshape(-1,3)
        np.savetxt(txt_filename,reshaped,fmt='%d',header='R G B',comments='')
        print(f"RGB image saved as text file: {txt_filename}")

    else:
        print("Unsupported image format or number of channels.")

img_to_array("network.png")

Error: Image not found or unable to read.
